/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Ads": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AdsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AdsBucketRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "BackendApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClerkClientPublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkClientSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkClientWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MyWeb": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "OpenAiApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ResendApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripePublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UnkeyApiId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UnkeyRootKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserKeys": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}